feat: Improving kube alias for reducing kubectl api pressure
Signed-off-by: Vincent Boutour <bob@vibioh.fr>

diff --git a/sources/kubernetes b/sources/kubernetes
--- a/sources/kubernetes
+++ b/sources/kubernetes
@@ -12,40 +12,25 @@ if command -v kubectl >/dev/null 2>&1; then
 
   if command -v fzf >/dev/null 2>&1; then
     kube() {
-      get_kube_restart() {
-        cat \
-          <(kubectl get deployments --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/deployment/" + .name') \
-          <(kubectl get daemonsets --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/daemonset/" + .name') \
-          <(kubectl get statefulsets --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/statefulset/" + .name') |
-          fzf --height=20 --ansi --reverse -1 --query="${1:-}"
+      get_kube_resources() {
+        local RESOURCE="${1:-}"
+        local QUERY="${2:-}"
+
+        if [[ -n ${RESOURCE} ]] && [[ -z ${QUERY} ]]; then
+          QUERY="${RESOURCE}"
+          RESOURCE=""
+        fi
+
+        if [[ -z ${RESOURCE} ]]; then
+          RESOURCE="deployments.apps"
+        fi
+
+        printf "%s/%s" "${RESOURCE}" "$(kubectl get "${RESOURCE}" --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/" + .name' | fzf --height=20 --ansi --reverse -1 --query="${QUERY}")"
       }
 
-      get_kube_log() {
-        cat \
-          <(kubectl get deployments --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/deployment/" + .name') \
-          <(kubectl get daemonsets --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/daemonset/" + .name') \
-          <(kubectl get statefulsets --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/statefulset/" + .name') \
-          <(kubectl get jobs --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/job/" + .name') |
-          fzf --height=20 --ansi --reverse -1 --query="${1:-}"
-      }
-
-      get_kube_service() {
-        kubectl get services --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/" + .name' | fzf --height=20 --ansi --reverse -1 --query="${1:-}"
-      }
-
-      get_kube_info() {
-        cat \
-          <(kubectl get deployments --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/deployment/" + .name') \
-          <(kubectl get daemonsets --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/daemonset/" + .name') \
-          <(kubectl get statefulsets --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/statefulsets/" + .name') \
-          <(kubectl get cronjobs --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/cronjob/" + .name') \
-          <(kubectl get jobs --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/job/" + .name') \
-          <(kubectl get pods --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/pod/" + .name') \
-          <(kubectl get services --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/service/" + .name') \
-          <(kubectl get configmaps --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/configmap/" + .name') \
-          <(kubectl get secrets --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/secret/" + .name') \
-          <(kubectl get ingresses.networking.k8s.io --all-namespaces --output=json | jq -r '.items[].metadata | .namespace + "/ingress.networking.k8s.io/" + .name') |
-          fzf --height=20 --ansi --reverse -1 --query="${1:-}"
+      print_and_execute() {
+        printf "%b%b%b\n" "${YELLOW}" "${@}" "${RESET}" 2>&1
+        eval "${@}"
       }
 
       local ACTION="${1}"
@@ -70,55 +55,51 @@ if command -v kubectl >/dev/null 2>&1; then
         ;;
 
       "forward")
-        IFS='/' read -r -a parts <<<"$(get_kube_service "${1:-}")"
+        IFS='/' read -r -a parts <<<"$(get_kube_resources "services" "${1:-}")"
 
-        if [[ -n ${parts[0]:-} ]]; then
+        if [[ -n ${parts[1]:-} ]]; then
           local KUBE_PORT
-          KUBE_PORT="$(kubectl --namespace="${parts[0]}" get services "${parts[1]}" --output=json | jq -r '.spec.ports[] | (.port|tostring) + "/" + .protocol' | fzf --height=20 --ansi --reverse -1 --query="${2:-}")"
+          KUBE_PORT="$(kubectl get "${parts[0]}" --namespace="${parts[1]}" "${parts[2]}" --output=json | jq -r '.spec.ports[] | (.port|tostring) + "/" + .protocol' | fzf --height=20 --ansi --reverse -1 --query="${2:-}")"
 
           if [[ -n ${KUBE_PORT:-} ]]; then
             IFS='/' read -r -a ports <<<"${KUBE_PORT}"
-            printf "%bForwarding %s from 4000 to %s%b\n" "${BLUE}" "${parts[0]}/${parts[1]}" "${ports[0]}" "${RESET}"
-            var_warning "kubectl --namespace='${parts[0]}' port-forward 'services/${parts[1]}' '4000:${ports[0]}'"
-            kubectl --namespace="${parts[0]}" port-forward "services/${parts[1]}" "4000:${ports[0]}"
+            printf "%bForwarding %s from 4000 to %s%b\n" "${BLUE}" "${parts[0]}/${parts[1]}/${parts[2]}" "${ports[0]}" "${RESET}"
+            print_and_execute "kubectl port-forward --namespace='${parts[1]}' '${parts[0]}/${parts[2]}' '4000:${ports[0]}'"
           fi
         fi
         ;;
 
       "image")
-        IFS='/' read -r -a parts <<<"$(get_kube_restart "${1:-}")"
+        IFS='/' read -r -a parts <<<"$(get_kube_resources "deployments.apps" "${1:-}")"
 
-        if [[ -n ${parts[0]:-} ]]; then
-          var_warning "kubectl --namespace='${parts[0]}' get '${parts[1]}' '${parts[2]}' --output=json | jq -r '.spec.template.spec.containers[].image'"
-          kubectl --namespace="${parts[0]}" get "${parts[1]}" "${parts[2]}" --output=json | jq -r '.spec.template.spec.containers[].image'
+        if [[ -n ${parts[1]:-} ]]; then
+          print_and_execute "kubectl get '${parts[0]}' --namespace='${parts[1]}' '${parts[2]}' --output=json | jq -r '.spec.template.spec.containers[].image'"
         fi
         ;;
 
       "info")
-        IFS='/' read -r -a parts <<<"$(get_kube_info "${1:-}")"
+        IFS='/' read -r -a parts <<<"$(get_kube_resources "${@}")"
 
-        if [[ -n ${parts[0]:-} ]]; then
-          var_warning "kubectl --namespace='${parts[0]}' get '${parts[1]}' '${parts[2]}' --output=yaml"
-          kubectl --namespace="${parts[0]}" get "${parts[1]}" "${parts[2]}" --output=yaml
+        if [[ -n ${parts[1]:-} ]]; then
+          print_and_execute "kubectl get '${parts[0]}' --namespace='${parts[1]}' '${parts[2]}' --output=yaml"
         fi
         ;;
 
       "log" | "logs")
-        IFS='/' read -r -a parts <<<"$(get_kube_log "${1:-}")"
+        IFS='/' read -r -a parts <<<"$(get_kube_resources "${@}")"
+        shift || true
         shift || true
 
-        if [[ -n ${parts[0]:-} ]]; then
+        if [[ -n ${parts[1]:-} ]]; then
           local PODS_LABELS
-          PODS_LABELS="$(kubectl --namespace="${parts[0]}" get "${parts[1]}" "${parts[2]}" --output=json | jq -r '.spec.selector.matchLabels | to_entries[] | .key + "=" + .value' | paste -sd, -)"
+          PODS_LABELS="$(kubectl get "${parts[0]}" --namespace="${parts[1]}" "${parts[2]}" --output=json | jq -r '.spec.selector.matchLabels | to_entries[] | .key + "=" + .value' | paste -sd, -)"
 
-          printf "%bTailing log for %b%s%b where labels are %b%s%b\n" "${BLUE}" "${GREEN}" "${parts[0]}/${parts[1]}/${parts[2]}" "${BLUE}" "${YELLOW}" "${PODS_LABELS}" "${RESET}"
+          printf "%bTailing logs for %b%s%b where labels are %b%s%b\n" "${BLUE}" "${GREEN}" "$(printf "%s" "${parts[@]}")" "${BLUE}" "${YELLOW}" "${PODS_LABELS}" "${RESET}"
 
-          if command -v stern 2>&1; then
-            var_warning "stern --namespace='${parts[0]}' --selector='${PODS_LABELS}' ${@}"
-            stern --namespace="${parts[0]}" --selector="${PODS_LABELS}" "${@}"
+          if command -v stern >/dev/null 2>&1; then
+            print_and_execute "stern --namespace='${parts[1]}' --selector='${PODS_LABELS}' --since=280h ${@}"
           else
-            var_warning "kubectl --namespace='${parts[0]}' logs --ignore-errors --prefix --all-containers=true --selector='${PODS_LABELS}' --follow ${@}"
-            kubectl --namespace="${parts[0]}" logs --ignore-errors --prefix --all-containers=true --selector="${PODS_LABELS}" --follow "${@}"
+            print_and_execute "kubectl logs --namespace='${parts[1]}' --ignore-errors --prefix --all-containers=true --selector='${PODS_LABELS}' --follow ${@}"
           fi
         fi
         ;;
@@ -128,16 +109,15 @@ if command -v kubectl >/dev/null 2>&1; then
         ;;
 
       "restart")
-        IFS='/' read -r -a parts <<<"$(get_kube_restart "${1:-}")"
-        if [[ -n ${parts[0]:-} ]]; then
-          var_warning "kubectl --namespace='${parts[0]}' rollout restart '${parts[1]}' '${parts[2]}'"
-          kubectl --namespace="${parts[0]}" rollout restart "${parts[1]}" "${parts[2]}"
+        IFS='/' read -r -a parts <<<"$(get_kube_resources "${@}")"
+
+        if [[ -n ${parts[1]:-} ]]; then
+          print_and_execute "kubectl rollout restart --namespace='${parts[1]}' '${parts[0]}' '${parts[2]}'"
         fi
         ;;
 
       "watch")
-        var_warning "kubectl get pods --all-namespaces --watch ${@}"
-        kubectl get pods --all-namespaces --watch "${@}"
+        print_and_execute "kubectl get pods --all-namespaces --watch ${@}"
         ;;
 
       *)
