feat: Adding kross command
Signed-off-by: Vincent Boutour <bob@vibioh.fr>

diff --git a/sources/kubernetes b/sources/kubernetes
--- a/sources/kubernetes
+++ b/sources/kubernetes
@@ -53,24 +53,6 @@ if command -v kubectl >/dev/null 2>&1; then
         fi
         ;;
 
-      "cross")
-        if [[ ${#} -lt 2 ]]; then
-          var_error "Usage: cross <context's regexp> command..."
-          return 1
-        fi
-
-        local CONTEXT_REGEXP="${1:-}"
-        shift
-
-        for ctx in $(kubectl config get-contexts --output name); do
-          if ! [[ ${ctx} =~ ${CONTEXT_REGEXP} ]]; then
-            continue
-          fi
-
-          var_print_and_run "kubectl --context '${ctx}' ${*}"
-        done
-        ;;
-
       "desc")
         IFS='/' read -r -a parts <<<"$(_kube_resources "${@}")"
 
@@ -209,7 +191,6 @@ if command -v kubectl >/dev/null 2>&1; then
 
         var_info "\nPossibles actions are                            | args\n"
         var_info " - context | Switch context                      | <context name>"
-        var_info " - cross   | Run command in multiple context     | <context regex> command..."
         var_info " - desc    | Describe an object                  | <object type or deployment name> <object name>?"
         var_info " - edit    | Edit an object                      | <object type or deployment name> <object name>?"
         var_info " - env     | Generate .env file from deployments | <deployment name> <container name>?"
@@ -228,7 +209,7 @@ if command -v kubectl >/dev/null 2>&1; then
 
     _fzf_complete_kube() {
       if [[ ${COMP_CWORD} -eq 1 ]]; then
-        mapfile -t COMPREPLY < <(compgen -W "context cross desc edit env forward image info logs ns restart watch" -- "${COMP_WORDS[COMP_CWORD]}")
+        mapfile -t COMPREPLY < <(compgen -W "context desc edit env forward image info logs ns restart watch" -- "${COMP_WORDS[COMP_CWORD]}")
         return
       fi
 
@@ -273,6 +254,56 @@ if command -v kubectl >/dev/null 2>&1; then
 
     [[ -n ${BASH} ]] && complete -F _fzf_complete_kube -o default -o bashdefault kube
   fi
+
+  kross() {
+    _kross_help() {
+      var_red "Usage: kross [options?] <context's regexp> ARGS..."
+
+      var_info "\nPossibles options are\n"
+      var_info " - -c Run alternative program than kubectl (with --context arg)"
+    }
+
+    if [[ ${#} -lt 2 ]]; then
+      _kross_help
+      return 1
+    fi
+
+    local COMMAND="kubectl"
+
+    OPTIND=0
+    while getopts ":c:" option; do
+      case "${option}" in
+      c)
+        COMMAND="${OPTARG}"
+        ;;
+      :)
+        printf "option -%s requires a value\n" "${OPTARG}" >&2
+        return 1
+        ;;
+      \?)
+        printf "option -%s is invalid\n" "${OPTARG}" >&2
+        return 2
+        ;;
+      *)
+        _kross_help
+        return 1
+        ;;
+      esac
+    done
+
+    shift $((OPTIND - 1))
+
+    local CONTEXT_REGEXP="${1:-}"
+    shift
+
+    for ctx in $(kubectl config get-contexts --output name); do
+      if ! [[ ${ctx} =~ ${CONTEXT_REGEXP} ]]; then
+        continue
+      fi
+
+      tmux_split_cmd "var_print_and_run \"${COMMAND} --context '${ctx}' ${*}\""
+    done
+  }
 fi
 
 if command -v helm >/dev/null 2>&1 && command -v delta >/dev/null 2>&1 && command -v fzf >/dev/null 2>&1 && command -v jq >/dev/null 2>&1 && command -v yq >/dev/null 2>&1 && command -v rg >/dev/null 2>&1; then
