refactor(kube): Fixing param not treated according to escape sequence
Signed-off-by: Vincent Boutour <bob@vibioh.fr>

diff --git a/sources/kube b/sources/kube
--- a/sources/kube
+++ b/sources/kube
@@ -10,8 +10,8 @@ kube() {
   local RESET='\033[0m'
 
   _kube_print_and_run() {
-    printf -- "%b%b%b\n" "${YELLOW}" "${@}" "${RESET}" 1>&2
-    eval "${*}"
+    printf -- "%b%s%b\n" "${YELLOW}" "${*}" "${RESET}" 1>&2
+    "${@}"
   }
 
   _kube_info() {
@@ -22,29 +22,30 @@ kube() {
     printf -- "%b%b %b\n" "${YELLOW}" "${*}" "${RESET}" 1>&2
   }
 
-  local KUBECTL_COMMAND="kubectl"
-  local KUBECTL_CONTEXT=""
+  local KUBECTL_COMMAND=("kubectl")
+  local KUBECTL_CONTEXT=()
   declare -a KUBECTL_CONTEXTS
 
   while [[ ${1:-} =~ ^--context ]]; do
     if [[ ${1:-} =~ ^--context && -n ${2:-} ]]; then
-      KUBECTL_CONTEXTS+=("${1} ${2}")
+      KUBECTL_CONTEXTS+=("${1}" "${2}")
       shift 2
+
+      if [[ ${#KUBECTL_CONTEXT} -eq 0 ]]; then
+        KUBECTL_CONTEXT+=("${1}" "${2}")
+      fi
     else
       KUBECTL_CONTEXTS+=("${1}")
       shift
-    fi
 
-    if [[ -z ${KUBECTL_CONTEXT} ]]; then
-      KUBECTL_CONTEXT="${KUBECTL_CONTEXTS[0]}"
+      if [[ ${#KUBECTL_CONTEXT} -eq 0 ]]; then
+        KUBECTL_CONTEXT+=("${1}")
+      fi
     fi
   done
 
-  local KUBECTL_FULL_CONTEXT
-  KUBECTL_FULL_CONTEXT="$(printf "%s " "${KUBECTL_CONTEXTS[@]}")"
-
-  if [[ -n ${KUBECTL_CONTEXT} ]]; then
-    KUBECTL_COMMAND+=" ${KUBECTL_CONTEXT}"
+  if [[ ${#KUBECTL_CONTEXT} -ne 0 ]]; then
+    KUBECTL_COMMAND+=("${KUBECTL_CONTEXT[@]}")
   fi
 
   local RESOURCE_TYPE
@@ -71,7 +72,7 @@ kube() {
     fi
 
     local KUBE_RESOURCE
-    KUBE_RESOURCE="$(${KUBECTL_COMMAND} get "${RESOURCE}" --all-namespaces --output=yaml | yq eval "${YAML_QUERY}" | fzf --height=20 --ansi --reverse --select-1 --query="${QUERY}")"
+    KUBE_RESOURCE="$("${KUBECTL_COMMAND[@]}" get "${RESOURCE}" --all-namespaces --output=yaml | yq eval "${YAML_QUERY}" | fzf --height=20 --ansi --reverse --select-1 --query="${QUERY}")"
 
     RESOURCE_TYPE="$(printf '%s' "${KUBE_RESOURCE}" | awk -F '/' '{ print $1 }')"
     RESOURCE_NAMESPACE="$(printf '%s' "${KUBE_RESOURCE}" | awk -F '/' '{ print $2 }')"
@@ -129,7 +130,7 @@ kube() {
         tmux setenv KUBECONFIG "${KUBECONFIG}"
       fi
 
-      _kube_print_and_run "kubectl config use-context ${CONTEXT}"
+      _kube_print_and_run kubectl config use-context "${CONTEXT}"
     fi
     ;;
 
@@ -137,7 +138,7 @@ kube() {
     _kube_resources "${@}"
 
     if [[ -n ${RESOURCE_NAME:-} ]]; then
-      _kube_print_and_run "${KUBECTL_COMMAND} describe ${RESOURCE_TYPE} --namespace=${RESOURCE_NAMESPACE} ${RESOURCE_NAME}"
+      _kube_print_and_run "${KUBECTL_COMMAND[@]}" describe "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}"
     fi
     ;;
 
@@ -145,7 +146,7 @@ kube() {
     _kube_resources "${@}"
 
     if [[ -n ${RESOURCE_NAME:-} ]]; then
-      _kube_print_and_run "${KUBECTL_COMMAND} edit ${RESOURCE_TYPE} --namespace=${RESOURCE_NAMESPACE} ${RESOURCE_NAME}"
+      _kube_print_and_run "${KUBECTL_COMMAND[@]}" edit "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}"
     fi
     ;;
 
@@ -154,11 +155,11 @@ kube() {
 
     if [[ -n ${RESOURCE_NAME:-} ]]; then
       local KUBE_CONTAINER
-      KUBE_CONTAINER="$(${KUBECTL_COMMAND} get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.spec.template.spec.containers[].name' | fzf --height=20 --ansi --reverse --select-1 --query="${2:-}" --prompt="Container:")"
+      KUBE_CONTAINER="$("${KUBECTL_COMMAND[@]}" get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.spec.template.spec.containers[].name' | fzf --height=20 --ansi --reverse --select-1 --query="${2:-}" --prompt="Container:")"
 
       local DEPLOYMENT_YAML
       DEPLOYMENT_YAML="$(mktemp)"
-      ${KUBECTL_COMMAND} get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml >"${DEPLOYMENT_YAML}"
+      "${KUBECTL_COMMAND[@]}" get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml >"${DEPLOYMENT_YAML}"
 
       KUBE_CONTAINER="${KUBE_CONTAINER}" yq eval '.spec.template.spec.containers[] | select(.name == strenv(KUBE_CONTAINER) and has("env")) | .env[] | select(has("value")) | .name + "=" + (.value | sub("[\n]", "\n"))' "${DEPLOYMENT_YAML}"
 
@@ -184,7 +185,7 @@ kube() {
           fi
           YQ_QUERY+=' | sub("[\n]", "\n")'
 
-          ${KUBECTL_COMMAND} get "${INLINE_RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${INLINE_RESOURCE_NAME}" --output=yaml | SECRET_KEY="${INLINE_REF_KEY}" yq eval '.data[strenv(SECRET_KEY)]| @base64d | sub("[\n]", "\n")'
+          "${KUBECTL_COMMAND[@]}" get "${INLINE_RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${INLINE_RESOURCE_NAME}" --output=yaml | SECRET_KEY="${INLINE_REF_KEY}" yq eval '.data[strenv(SECRET_KEY)]| @base64d | sub("[\n]", "\n")'
         done <<<"${INLINE_REFS}"
       fi
 
@@ -205,7 +206,7 @@ kube() {
           YQ_QUERY+=' | sub("[\n]", "\n"))'
 
           _kube_warning "${ENVFROM_RESOURCE_TYPE} ${RESOURCE_NAMESPACE}/${ENVFROM_RESOURCE_NAME}"
-          ${KUBECTL_COMMAND} get "${ENVFROM_RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${ENVFROM_RESOURCE_NAME}" --output=yaml | yq eval "${YQ_QUERY}"
+          "${KUBECTL_COMMAND[@]}" get "${ENVFROM_RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${ENVFROM_RESOURCE_NAME}" --output=yaml | yq eval "${YQ_QUERY}"
         done <<<"${ENV_FROMS}"
       fi
 
@@ -218,11 +219,11 @@ kube() {
 
       if [[ -n ${FIELD_REFS:-} ]]; then
         local PODS_LABELS
-        PODS_LABELS="$(${KUBECTL_COMMAND} get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.spec.selector.matchLabels | to_entries | .[] | .key + "=" + .value' | paste -sd, -)"
+        PODS_LABELS="$("${KUBECTL_COMMAND[@]}" get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.spec.selector.matchLabels | to_entries | .[] | .key + "=" + .value' | paste -sd, -)"
 
         local POD_YAML
         POD_YAML="$(mktemp)"
-        ${KUBECTL_COMMAND} get pods --namespace="${RESOURCE_NAMESPACE}" "--selector=${PODS_LABELS}" --output=yaml | yq eval '[.items[] | select(.status.phase == "Running")] | .[0]' >"${POD_YAML}"
+        "${KUBECTL_COMMAND[@]}" get pods --namespace="${RESOURCE_NAMESPACE}" "--selector=${PODS_LABELS}" --output=yaml | yq eval '[.items[] | select(.status.phase == "Running")] | .[0]' >"${POD_YAML}"
 
         _kube_warning "Values from first 'Running' pod found"
         while read -r fieldRef; do
@@ -246,16 +247,16 @@ kube() {
 
     if [[ -n ${RESOURCE_NAME:-} ]]; then
       local KUBE_PORT
-      KUBE_PORT="$(${KUBECTL_COMMAND} get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.spec.ports[] | .targetPort' | fzf --height=20 --ansi --reverse --select-1 --query="${3:-}" --prompt="Port:")"
+      KUBE_PORT="$("${KUBECTL_COMMAND[@]}" get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.spec.ports[] | .targetPort' | fzf --height=20 --ansi --reverse --select-1 --query="${3:-}" --prompt="Port:")"
 
       if [[ -n ${KUBE_PORT:-} ]]; then
         local LOCAL_PORT="${2:-4000}"
 
         if command -v kmux >/dev/null 2>&1; then
-          _kube_print_and_run "kmux ${KUBECTL_FULL_CONTEXT} --namespace=${RESOURCE_NAMESPACE} port-forward ${RESOURCE_TYPE} ${RESOURCE_NAME} ${LOCAL_PORT}:${KUBE_PORT}"
+          _kube_print_and_run kmux "${KUBECTL_CONTEXTS[@]}" --namespace="${RESOURCE_NAMESPACE}" port-forward "${RESOURCE_TYPE}" "${RESOURCE_NAME}" "${LOCAL_PORT}:${KUBE_PORT}"
         else
           printf "%bForwarding %s from %s to %s%b\n" "${BLUE}" "${RESOURCE_TYPE}/${RESOURCE_NAMESPACE}/${RESOURCE_NAME}" "${LOCAL_PORT}" "${KUBE_PORT}" "${RESET}"
-          _kube_print_and_run "${KUBECTL_COMMAND} port-forward --namespace=${RESOURCE_NAMESPACE} ${RESOURCE_TYPE}/${RESOURCE_NAME} ${LOCAL_PORT}:${KUBE_PORT}"
+          _kube_print_and_run "${KUBECTL_COMMAND[@]}" port-forward --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_TYPE}/${RESOURCE_NAME}" "${LOCAL_PORT}:${KUBE_PORT}"
         fi
       fi
     fi
@@ -270,9 +271,9 @@ kube() {
 
     if [[ -n ${RESOURCE_NAME:-} ]]; then
       if command -v kmux >/dev/null 2>&1; then
-        _kube_print_and_run "kmux ${KUBECTL_FULL_CONTEXT} --namespace=${RESOURCE_NAMESPACE} image ${RESOURCE_TYPE} ${RESOURCE_NAME}"
+        _kube_print_and_run kmux "${KUBECTL_CONTEXTS[@]}" --namespace="${RESOURCE_NAMESPACE}" image "${RESOURCE_TYPE}" "${RESOURCE_NAME}"
       else
-        _kube_print_and_run "${KUBECTL_COMMAND} get ${RESOURCE_TYPE} --namespace=${RESOURCE_NAMESPACE} ${RESOURCE_NAME} --output=yaml | yq eval '.spec.template.spec.containers[].image'"
+        _kube_print_and_run "${KUBECTL_COMMAND[@]}" get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.spec.template.spec.containers[].image'
       fi
     fi
     ;;
@@ -286,7 +287,7 @@ kube() {
         QUERY=".data[] |= @base64d"
       fi
 
-      _kube_print_and_run "${KUBECTL_COMMAND} get ${RESOURCE_TYPE} --namespace=${RESOURCE_NAMESPACE} ${RESOURCE_NAME} --output=yaml | yq eval --prettyPrint '${QUERY}'"
+      _kube_print_and_run "${KUBECTL_COMMAND[@]}" get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval --prettyPrint "${QUERY}"
     fi
     ;;
 
@@ -307,29 +308,29 @@ kube() {
 
     if [[ -n ${RESOURCE_NAME:-} ]]; then
       if [[ ${RESOURCE_TYPE} =~ ^(cronjob|daemonset|deployment|job|pod|namespace|service|node|statefulset)s? ]] && command -v kmux >/dev/null 2>&1; then
-        _kube_print_and_run "kmux ${KUBECTL_FULL_CONTEXT} --namespace '${RESOURCE_NAMESPACE}' log ${RESOURCE_TYPE} ${RESOURCE_NAME} --since=24h ${*}"
+        _kube_print_and_run kmux "${KUBECTL_CONTEXTS[@]}" --namespace "${RESOURCE_NAMESPACE}" log "${RESOURCE_TYPE}" "${RESOURCE_NAME}" --since=24h "${@}"
       else
         local PODS_LABELS
 
         if [[ ${RESOURCE_TYPE} =~ ^cronjobs? ]]; then
-          PODS_LABELS="job-name in ($(${KUBECTL_COMMAND} get jobs --namespace="${RESOURCE_NAMESPACE}" --output yaml | OWNER_NAME="${RESOURCE_NAME}" yq eval '.items[] | select(.metadata.ownerReferences[].name == strenv(OWNER_NAME)) | .metadata.name' | paste -sd, -))"
+          PODS_LABELS="job-name in ($("${KUBECTL_COMMAND[@]}" get jobs --namespace="${RESOURCE_NAMESPACE}" --output yaml | OWNER_NAME="${RESOURCE_NAME}" yq eval '.items[] | select(.metadata.ownerReferences[].name == strenv(OWNER_NAME)) | .metadata.name' | paste -sd, -))"
         elif [[ ${RESOURCE_TYPE} =~ ^jobs? ]]; then
           PODS_LABELS="job-name=${RESOURCE_NAME}"
         elif [[ ${RESOURCE_TYPE} =~ ^(daemonset|deployment|statefulset)s? ]]; then
-          PODS_LABELS="$(${KUBECTL_COMMAND} get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.spec.selector.matchLabels | to_entries | .[] | .key + "=" + .value' | paste -sd, -)"
+          PODS_LABELS="$("${KUBECTL_COMMAND[@]}" get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.spec.selector.matchLabels | to_entries | .[] | .key + "=" + .value' | paste -sd, -)"
         else
-          PODS_LABELS="$(${KUBECTL_COMMAND} get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.metadata.labels | to_entries | .[] | .key + "=" + .value' | paste -sd, -)"
+          PODS_LABELS="$("${KUBECTL_COMMAND[@]}" get "${RESOURCE_TYPE}" --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_NAME}" --output=yaml | yq eval '.metadata.labels | to_entries | .[] | .key + "=" + .value' | paste -sd, -)"
         fi
 
         printf "%bTailing logs for %b%s%b where labels are %b%s%b\n" "${BLUE}" "${GREEN}" "${RESOURCE_TYPE}/${RESOURCE_NAMESPACE}/${RESOURCE_NAME}" "${BLUE}" "${YELLOW}" "${PODS_LABELS}" "${RESET}"
 
-        _kube_print_and_run "${KUBECTL_COMMAND} logs --namespace=${RESOURCE_NAMESPACE} --ignore-errors --prefix --selector='${PODS_LABELS}' --follow --since=24h ${*}"
+        _kube_print_and_run "${KUBECTL_COMMAND[@]}" logs --namespace="${RESOURCE_NAMESPACE}" --ignore-errors --prefix --selector="${PODS_LABELS}" --follow --since=24h "${@}"
       fi
     fi
     ;;
 
   "ns")
-    ${KUBECTL_COMMAND} get namespaces --output=yaml | yq eval '.items[].metadata.name' | fzf --height=20 --ansi --reverse --select-1 --query="${1:-}" | xargs ${KUBECTL_COMMAND} config set-context --current --namespace
+    "${KUBECTL_COMMAND[@]}" get namespaces --output=yaml | yq eval '.items[].metadata.name' | fzf --height=20 --ansi --reverse --select-1 --query="${1:-}" | xargs "${KUBECTL_COMMAND[@]}" config set-context --current --namespace
     ;;
 
   "restart")
@@ -337,12 +338,12 @@ kube() {
 
     if [[ -n ${RESOURCE_NAME:-} ]]; then
       if command -v kmux >/dev/null 2>&1; then
-        _kube_print_and_run "kmux ${KUBECTL_FULL_CONTEXT} --namespace '${RESOURCE_NAMESPACE}' restart ${RESOURCE_TYPE} ${RESOURCE_NAME}"
+        _kube_print_and_run kmux "${KUBECTL_CONTEXTS[@]}" --namespace="${RESOURCE_NAMESPACE}" restart "${RESOURCE_TYPE}" "${RESOURCE_NAME}"
       else
         if [[ ${RESOURCE_TYPE} =~ ^jobs? ]]; then
-          _kube_print_and_run "${KUBECTL_COMMAND} get --namespace=${RESOURCE_NAMESPACE} ${RESOURCE_TYPE} ${RESOURCE_NAME} --output yaml | yq eval 'del(.spec.selector)' | yq eval 'del(.spec.template.metadata.labels)' | ${KUBECTL_COMMAND} replace --force --filename -"
+          _kube_print_and_run "${KUBECTL_COMMAND[@]}" get --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_TYPE}" "${RESOURCE_NAME}" --output yaml | yq eval 'del(.spec.selector)' | yq eval 'del(.spec.template.metadata.labels)' | "${KUBECTL_COMMAND[@]}" replace --force --filename -
         else
-          _kube_print_and_run "${KUBECTL_COMMAND} rollout restart --namespace=${RESOURCE_NAMESPACE} ${RESOURCE_TYPE} ${RESOURCE_NAME}"
+          _kube_print_and_run "${KUBECTL_COMMAND[@]}" rollout restart --namespace="${RESOURCE_NAMESPACE}" "${RESOURCE_TYPE}" "${RESOURCE_NAME}"
         fi
       fi
     fi
@@ -351,20 +352,14 @@ kube() {
 
   "watch")
     if command -v kmux >/dev/null 2>&1; then
-      _kube_print_and_run "kmux ${KUBECTL_FULL_CONTEXT} watch ${*}"
+      _kube_print_and_run kmux "${KUBECTL_CONTEXTS[@]}" watch "${@}"
     else
-      _kube_print_and_run "${KUBECTL_COMMAND} get pods --watch ${*}"
+      _kube_print_and_run "${KUBECTL_COMMAND[@]}" get pods --watch "${@}"
     fi
     ;;
 
   *)
-    if [[ ${#KUBECTL_CONTEXTS} -gt 1 ]]; then
-      for context in "${KUBECTL_CONTEXTS[@]}"; do
-        _kube_print_and_run "kubectl ${context} ${ACTION} ${*}"
-      done
-    else
-      _kube_print_and_run "${KUBECTL_COMMAND} ${ACTION} ${*}"
-    fi
+    _kube_print_and_run "${KUBECTL_COMMAND[@]}" "${ACTION}" "${@}"
 
     return 1
     ;;
